default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 127.0.0.1
  user: postgres
  password: 123123

development:
  <<: *default
  database: bet_development

test:
  <<: *default
  database: bet_test

production:
  <<: *default
  database: bet_production
  url: <%= ENV['DATABASE_URL'] %>